---
- hosts: all
  gather_facts: false
  vars:
    num_messages: 1000
    sleep_interval: 2
    message_size: 1024
  tasks:
    - name: Print a large debug message
      debug:
        msg: "{{ 'X' * message_size }} - Message {{ item + 1 }} of {{ num_messages }}"
      loop: "{{ range(0, num_messages | int) | list }}"

    - name: Sleep between messages
      pause:
        seconds: "{{ sleep_interval | int }}"
      loop: "{{ range(0, num_messages | int) | list }}"
