---
- hosts: all
  gather_facts: false
  vars:
    num_messages: 1000
    sleep_interval: 2
    message_size: 1024
  tasks:
    - name: Generate chatty debug messages with sleep
      include_tasks: chatty_block.yml
      vars:
        message_number: "{{ item + 1 }}"
        message_size: "{{ message_size }}"
        sleep_interval: "{{ sleep_interval }}"
        num_messages: "{{ num_messages }}"
      loop: "{{ range(0, num_messages | int) | list }}"
